### PR TITLE
- update cron chapter

### PR DESCRIPTION
**Pull request by maks-oleksyuk**
I decided to refresh my knowledge of this topic and update the page at the same time.

I hope it will be useful for someone.

### CODE REVIEW

**Comment by selwynpolit** [comment]
@maks-oleksyuk I like where this is going.  Are you still editing?  I noticed some items that look incomplete near the bottom of the file.

**Comment by maks-oleksyuk** [comment]
At the moment, I have finished writing it. 

I tried to make the test clear and informative,
Which parts look incomplete?

**Comment by selwynpolit** [comment]
In the diff, this is how it displays.  it looks like the parentheses are missing on these links.  

image

**Comment by selwynpolit** [comment]
When I look with the rich text diff, the links all seem fine.  Ah, it seems that you can separate the links and make a list of them at the bottom of the file.  I had no idea this was possible in markdown.  I'll try merge and see how it looks.  Yes, the writing is very clear.  Nice work.

**Comment by selwynpolit** [comment]
Yeah, it is great!  As usual Maks.  Amazing work.  I'm sure it will be very helpful to many people.

**Pull request merged**
